# Generated by Django 3.1.5 on 2021-06-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AboutUs_description', models.TextField(max_length=200)),
                ('Sub_header', models.CharField(max_length=25)),
                ('Sub_Header_description', models.TextField()),
                ('AboutUs_image', models.ImageField(upload_to='abu')),
            ],
        ),
        migrations.CreateModel(
            name='Car_des',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_description', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Carsoul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(default=954)),
                ('width', models.IntegerField(default=1982)),
                ('Carsoul_image', models.ImageField(height_field='height', upload_to='Cas', width_field='width')),
            ],
        ),
        migrations.CreateModel(
            name='list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Why_Choose_us_list', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Heading', models.TextField(max_length=100)),
                ('Project_Image', models.ImageField(upload_to='proj')),
                ('category_of_projects', models.CharField(choices=[('PHG', 'Photography'), ('BRN', 'Branding'), ('WB', 'Web')], default='PHG', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Services_Image', models.ImageField(upload_to='ser')),
                ('Services_title', models.CharField(max_length=40)),
                ('Services_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='whyUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('What_we_do', models.TextField()),
                ('Why_Choose_us_header', models.TextField()),
                ('Why_Choose_us_image', models.ImageField(upload_to='abu')),
            ],
        ),
    ]
