# Generated by Django 3.1.5 on 2021-06-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_team_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Team_descrption',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='Team_member_facebook_link',
            field=models.URLField(blank=True, db_index=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='Team_member_google_plus_link',
            field=models.URLField(blank=True, db_index=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='Team_member_twitter_link',
            field=models.URLField(blank=True, db_index=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='Video_heading',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
