# Generated by Django 3.1.5 on 2021-07-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20210627_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='Display_Project_heading',
        ),
        migrations.AlterField(
            model_name='projects',
            name='Project_Heading',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
