# Generated by Django 3.2.6 on 2021-09-15 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_auto_20210912_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whyus',
            options={'verbose_name': 'What we do'},
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='Sub_header',
        ),
        migrations.RemoveField(
            model_name='whyus',
            name='Why_Choose_us_header',
        ),
        migrations.RemoveField(
            model_name='whyus',
            name='Why_Choose_us_image',
        ),
    ]
