# Generated by Django 3.2.6 on 2021-09-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_auto_20210915_2144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carsoul',
            options={'verbose_name': 'Carsoul_image_name'},
        ),
        migrations.RemoveField(
            model_name='carsoul',
            name='height',
        ),
        migrations.RemoveField(
            model_name='carsoul',
            name='width',
        ),
        migrations.AddField(
            model_name='carsoul',
            name='Carsoul_image_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='carsoul',
            name='Carsoul_image',
            field=models.ImageField(upload_to='Cas'),
        ),
    ]
